# Configuration for Robot Odometry

two_d_mode: true
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: pose_hector
odom0_config: [true, true, true, # x, y, z
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false

imu0: imu_hector
imu0_config: [false, false, false, # x, y, z
               false, false, false,
               false, false, false,
               false, false, false,
               true, true, true]
imu0_diferential: false
# I need robot state publisher information to convert the data to base link